<a href="https://colab.research.google.com/github/RaghaviVasireddy/100Days-ML-DL/blob/main/Day3_Multilayer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Ovarian Cancer Detection using Multi Layer Perceptron (MLP)

## Project Overview
This project implements a **Machine Learning model using a Multi Layer Perceptron (MLP)** to classify ovarian cancer data. The dataset is preprocessed and normalized using **MinMaxScaler**, and then split into training and testing datasets.

The goal of this project is to demonstrate how neural networks can be applied for **medical data classification**.

---

## Dataset
Dataset used: `ovariantotal.csv`

The dataset contains multiple medical features and a target column:

- **TYPE** → Target variable representing cancer type/class.

---

## Technologies Used

- Python
- Pandas
- NumPy
- Scikit-learn
- Google Colab / Jupyter Notebook

---

## Project Workflow

1. Import required libraries
2. Load ovarian cancer dataset
3. Data exploration
4. Feature selection
5. Data normalization using **MinMaxScaler**
6. Train-Test split
7. Multi Layer Perceptron model training
8. Model evaluation

In [9]:
#importing the packages
import pandas as pd
import numpy as np
cancer=pd.read_csv('/content/drive/MyDrive/ovariantotal.csv')
cancer.head()

,AFP,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,BUN,...,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA,TYPE
0,3.58,19.36,47,45.4,56,11,24,0.01,0.30,5.35,...,0.09,13.4,1.46,74,2.64,13.7,5.5,73.9,396.4,0
1,34.24,23.98,61,39.9,95,9,13,0.02,0.30,3.21,...,0.30,11.2,1.09,304,4.89,12.7,6.8,72.0,119.2,0
2,1.50,18.40,39,45.4,77,9,18,0.03,0.60,3.80,...,0.13,15.2,0.97,112,4.62,12.0,14.8,77.9,209.2,0
3,2.75,16.60,45,39.2,26,16,17,0.05,0.74,5.27,...,0.25,17.4,1.25,339,4.01,14.6,10.9,66.1,215.6,0
4,2.36,19.97,45,35.0,47,21,27,0.01,0.10,4.89,...,0.28,11.9,0.94,272,4.40,13.4,5.3,66.5,206.0,0

In [10]:
cancer.tail()

,AFP,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,BUN,...,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA,TYPE
344,2.09,20.91,52,48.6,65,40,30,0.00,0.0,4.29,...,0.22,10.8,0.99,219,4.56,11.9,10.7,80.4,241.5,1
345,2.00,12.14,37,46.1,49,9,20,0.00,0.0,3.12,...,0.31,17.3,0.95,262,4.24,17.7,17.2,73.5,240.5,1
346,2.83,19.23,59,45.8,83,9,16,0.02,0.6,4.38,...,0.21,10.4,1.00,221,4.89,11.6,13.8,68.4,209.5,1
347,1.84,27.22,30,47.8,64,26,22,0.03,0.3,3.61,...,0.42,13.4,1.31,398,5.35,12.5,11.3,76.0,285.7,1
348,1.61,13.00,39,44.9,68,7,13,0.01,0.2,4.38,...,0.23,11.0,1.10,224,4.13,12.1,8.3,68.6,184.9,1

In [ ]:
cancer.head(10)

,AFP,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,BUN,...,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA,TYPE
0,3.58,19.36,47,45.40,56,11,24,0.01,0.30,5.35,...,0.090,13.4,1.46,74,2.64,13.7,5.50,73.90,396.4,0
1,34.24,23.98,61,39.90,95,9,13,0.02,0.30,3.21,...,0.300,11.2,1.09,304,4.89,12.7,6.80,72.00,119.2,0
2,1.50,18.40,39,45.40,77,9,18,0.03,0.60,3.80,...,0.130,15.2,0.97,112,4.62,12.0,14.80,77.90,209.2,0
3,2.75,16.60,45,39.20,26,16,17,0.05,0.74,5.27,...,0.250,17.4,1.25,339,4.01,14.6,10.90,66.10,215.6,0
4,2.36,19.97,45,35.00,47,21,27,0.01,0.10,4.89,...,0.280,11.9,0.94,272,4.40,13.4,5.30,66.50,206.0,0
5,3.79,17.39,44,32.90,118,51,32,0.02,0.42,4.47,...,0.265,19.1,0.68,279,4.44,21.7,8.10,72.30,218.2,0
6,4.93,21.87,53,41.08,77,18,19,0.02,0.50,2.60,...,0.180,16.8,1.50,148,4.64,12.1,9.09,71.08,151.9,0
7,3.03,24.05,76,50.40,76,16,23,0.04,0.50,5.05,...,0.240,15.1,1.17,205,4.61,12.8,7.40,77.00,334.2,0
8,1.01,23.63,38,36.30,64,62,47,0.00,0.40,2.50,...,0.250,17.4,1.01,277,4.96,19.3,5.50,79.60,140.1,0
9,4.70,16.86,30,40.80,77,16,12,0.08,1.23,5.78,...,0.228,16.9,1.46,348,5.05,14.0,8.40,71.90,210.3,0

In [ ]:
cancer.shape

(349, 50)

In [11]:
X=cancer.drop('TYPE',axis=1)
Y=cancer['TYPE']

In [12]:
from sklearn import preprocessing
min_max_scaler=preprocessing.MinMaxScaler()
X_scale=min_max_scaler.fit_transform(X)
print(X_scale)

[[2.45578349e-03 4.85071876e-01 4.70588235e-01 ... 8.37988827e-02
  7.60667904e-01 5.60447761e-01]
 [2.78074070e-02 6.55363067e-01 6.76470588e-01 ... 1.20111732e-01
  7.25417440e-01 4.32835821e-02]
 [7.35908185e-04 4.49686694e-01 3.52941176e-01 ... 3.43575419e-01
  8.34879406e-01 2.11194030e-01]
 ...
 [1.83563615e-03 4.80280133e-01 6.47058824e-01 ... 3.15642458e-01
  6.58627087e-01 2.11753731e-01]
 [1.01704165e-03 7.74788058e-01 2.20588235e-01 ... 2.45810056e-01
  7.99628942e-01 3.53917910e-01]
 [8.26863129e-04 2.50645042e-01 3.52941176e-01 ... 1.62011173e-01
  6.62337662e-01 1.65858209e-01]]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_scale,Y,test_size=0.20,random_state=0)
#random state split remain same
#test size 20% training size 80%

In [2]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(32,activation='relu',input_dim=49))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=32,epochs=15)

Epoch 1/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6022 - loss: 0.6837
Epoch 2/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6774 - loss: 0.6600
Epoch 3/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7025 - loss: 0.6415
Epoch 4/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7312 - loss: 0.6210
Epoch 5/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7419 - loss: 0.5990
Epoch 6/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7563 - loss: 0.5774
Epoch 7/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7527 - loss: 0.5563
Epoch 8/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7563 - loss: 0.5377
Epoch 9/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7706 - loss: 0.5173
Epoch 10/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7634 - loss: 0.5035
Epoch 11/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7957 - loss: 0.4885
Epoch 12/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7885 - loss: 0.4792
Epoch 13/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8100 - loss: 0.4709
Epoch 14/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8100 - loss: 0.4580
Epoch 15/15
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8065 - loss: 0.4506

In [15]:
y_pred=model.predict(X_test)
y_pred

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

array([[0.7491972 ],
       [0.26550022],
       [0.6670795 ],
       [0.07350514],
       [0.86706936],
       [0.8733666 ],
       [0.86606467],
       [0.13844918],
       [0.1147704 ],
       [0.78778464],
       [0.64209163],
       [0.15199506],
       [0.8478322 ],
       [0.34283254],
       [0.09412929],
       [0.58902866],
       [0.5119821 ],
       [0.7437244 ],
       [0.8961949 ],
       [0.48056272],
       [0.66907907],
       [0.7988736 ],
       [0.30724055],
       [0.818458  ],
       [0.05740397],
       [0.77067876],
       [0.06164795],
       [0.1659879 ],
       [0.11020558],
       [0.85275155],
       [0.50007355],
       [0.2756917 ],
       [0.1436016 ],
       [0.21115604],
       [0.11222244],
       [0.03359379],
       [0.5863991 ],
       [0.73756593],
       [0.15171923],
       [0.3311888 ],
       [0.83055127],
       [0.8241013 ],
       [0.78634393],
       [0.8025343 ],
       [0.8505012 ],
       [0.05103298],
       [0.3259871 ],
       [0.76249   ],
       [0.08906942],
       [0.36271122],
       [0.7606766 ],
       [0.70068794],
       [0.37025803],
       [0.31878766],
       [0.56561005],
       [0.8045255 ],
       [0.3062618 ],
       [0.9103599 ],
       [0.25610226],
       [0.80244637],
       [0.86361814],
       [0.24188273],
       [0.27355736],
       [0.8806572 ],
       [0.05539038],
       [0.44027597],
       [0.1705908 ],
       [0.61508435],
       [0.5549253 ],
       [0.251113  ]], dtype=float32)

In [18]:
y_pred=np.where(y_pred>0.5,1,0)
y_pred=y_pred.astype(int)
import numpy as np
np.column_stack((y_pred,y_test))

array([[1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0]])

In [22]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[31 10]
 [ 3 26]]
0.8142857142857143